spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.0.8.3:3306/generator?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: jh@123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat,wall
    initial-size: 3
    min-idle: 1
    max-active: 20
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    validation-query: select 'x'
    max-wait: 6000
    pool-prepared-statements: true
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 60000
    web-stat-filter:
      enabled: true
      url-pattern: "/*"


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: org.ccs.opendfl.mysql
  mapper-locations: classpath:mappers/*/*.xml

# TkMapper
mapper:
  identity: MYSQL
  mappers: tk.mybatis.mapper.common.BaseMapper
  not-empty: true
  enum-as-simple-type: true

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    info:
      enabled: true

logging:
  level:
    root: INFO
    org:
      ccs:
        opendfl: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(-){faint} %clr([%14.14t]){faint} %clr(%-40.40logger.%13.13M){cyan} %clr(%3.3L) %clr(:){faint} %msg%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

